### ISSUE TITLE
Which dataset is AG203.csv?

### ISSUE THREAD

**Issue by andrefs** [MohamedAliHadjTaieb/Semantic-measure-assessment-review-study#1]
Hello,

I was searching GitHub for semantic similarity/relatedness datasets and I found this repository.
Thanks for compiling this list!

I got interested in the file [AG203.csv](https://github.com/MohamedAliHadjTaieb/Semantic-measure-assessment-review-study/blob/master/DataSets/English/Semantic%20Similarity/AG203.csv) because it seems to include pairs from Miller and Charles/Rubenstein and Goodenough.

But I don't understand which dataset is this. Where did you get it, and who are the authors?
The list on the README.md does not list this dataset on the English section.

Can you help me? Thanks!

**Comment by zesch** [comment]
This is from: 
`Agirre E, Alfonseca E, Hall K, Kravalova J, Paşca M, Soroa A (2009) A study on similarity and relatedness using distributional and wordnet-based approaches. In: Proceedings of human language technologies: the 2009 annual conference of the North American chapter of the association for computational lin- guistics, NAACL’09. Association for Computational Linguistics, Stroudsburg, PA, USA, pp 19–27`

Please also refer to Table 3 here:
https://link.springer.com/content/pdf/10.1007/s10462-019-09796-3.pdf

**Comment by andrefs** [comment]
Ah perfect, many thanks! :ok_hand:
